spring:
  datasource:
      url: jdbc:mysql://10.60.2.175:3306/shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
